#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

Dotenv\Dotenv::create(__DIR__)->load();

$imageAnnotator = new Google\Cloud\Vision\V1\ImageAnnotatorClient();

$path = $argv[1];

$annotation = $imageAnnotator->documentTextDetection(file_get_contents($path))->getFullTextAnnotation();

if (! $annotation) {
    echo 'No text found.'.PHP_EOL;
    exit(1);
}

$savePath = $argv[2] ?? explode('.', $path)[0].'-text.txt';

file_put_contents($savePath, $annotation->getText());

echo 'Results saved to "'.$savePath.'"'.PHP_EOL;
